//------------------------------------------------------------------------------
// <auto-generated>
//     This file is regenerated by Tools/CMS/Reload.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.CMS.Runtime
{
    public static class CMSPath
    {
    }
}
