using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Game.CMS.Runtime;
using UnityEditor;
using UnityEngine;

namespace Game.CMS.Editor
{
    public sealed class CMSGenerator : AssetPostprocessor
    {
        private const string ResourcesFolderPath = "_Game/Resources/CMS";
        private const string OutputFolderPath = "_Game/Scripts/CMS/Runtime";
        private const string OutputClassName = "CMSPath";

        private static readonly HashSet<string> CSharpKeywords = new()
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
            "void", "volatile", "while"
        };

        [MenuItem("Tools/CMS/Reload")]
        private static void Reload()
        {
            CMSPrefabEditor.RefreshAllEntityIds();
            CMSAssetEditor.RefreshAllEntityIds();
            AssetDatabase.SaveAssets();
            GenerateResourceClass();
            CMSContainer.Reload();
            AssetDatabase.SaveAssets();
        }

        private static void GenerateResourceClass()
        {
            string resourcesPath = Path.Combine(Application.dataPath, ResourcesFolderPath);
            string outputDirectory = Path.Combine(Application.dataPath, OutputFolderPath);
            string outputPath = Path.Combine(outputDirectory, $"{OutputClassName}.cs");

            Directory.CreateDirectory(outputDirectory);

            var code = new StringBuilder(2048);
            GenerateFileHeader(code);
            GenerateNamespaceAndClass(code, resourcesPath);
            File.WriteAllText(outputPath, code.ToString());
            AssetDatabase.ImportAsset($"Assets/{OutputFolderPath}/{OutputClassName}.cs");

            Debug.Log($"[CMS] Generated {OutputClassName} at Assets/{OutputFolderPath}/{OutputClassName}.cs");
        }

        private static void GenerateFileHeader(StringBuilder builder)
        {
            builder.AppendLine("//------------------------------------------------------------------------------");
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("//     This file is regenerated by Tools/CMS/Reload.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("//------------------------------------------------------------------------------");
            builder.AppendLine();
        }

        private static void GenerateNamespaceAndClass(StringBuilder builder, string resourcesPath)
        {
            builder.AppendLine("namespace Game.CMS.Runtime");
            builder.AppendLine("{");
            builder.AppendLine($"    public static class {OutputClassName}");
            builder.AppendLine("    {");

            if (Directory.Exists(resourcesPath))
                GenerateFolderConstants(resourcesPath, builder, "        ");

            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        private static void GenerateFolderConstants(string folderPath, StringBuilder builder, string indent)
        {
            var usedIdentifiers = new HashSet<string>();

            foreach (string subFolder in Directory.GetDirectories(folderPath).OrderBy(path => path))
            {
                string folderName = SanitizeIdentifier(Path.GetFileName(subFolder));
                EnsureUniqueIdentifier(usedIdentifiers, folderName, subFolder);
                builder.AppendLine($"{indent}public static class {folderName}");
                builder.AppendLine($"{indent}{{");
                GenerateFolderConstants(subFolder, builder, indent + "    ");
                builder.AppendLine($"{indent}}}");
            }

            foreach (string file in Directory.GetFiles(folderPath)
                         .Where(IsCMSEntityFile)
                         .OrderBy(path => path))
            {
                string fileName = SanitizeIdentifier(Path.GetFileNameWithoutExtension(file));
                string relativePath = GetResourceRelativePath(file);
                if (!string.IsNullOrEmpty(fileName) && relativePath != null)
                {
                    EnsureUniqueIdentifier(usedIdentifiers, fileName, file);
                    builder.AppendLine($"{indent}public const string {fileName} = \"{relativePath}\";");
                }
            }
        }

        private static bool IsCMSEntityFile(string fullPath)
        {
            string normalizedPath = fullPath.Replace('\\', '/');
            string assetsPath = Application.dataPath.Replace('\\', '/');
            if (!normalizedPath.StartsWith(assetsPath + "/", StringComparison.OrdinalIgnoreCase))
                return false;

            string assetPath = "Assets" + normalizedPath.Substring(assetsPath.Length);
            string extension = Path.GetExtension(normalizedPath);

            if (extension.Equals(".asset", StringComparison.OrdinalIgnoreCase))
                return AssetDatabase.LoadAssetAtPath<CMSAsset>(assetPath) != null;

            if (!extension.Equals(".prefab", StringComparison.OrdinalIgnoreCase))
                return false;

            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
            return prefab != null && prefab.GetComponent<CMSPrefab>() != null;
        }

        private static void EnsureUniqueIdentifier(HashSet<string> usedIdentifiers, string identifier, string path)
        {
            if (!usedIdentifiers.Add(identifier))
                throw new InvalidOperationException($"Duplicate CMSPath identifier '{identifier}' in '{path}'.");
        }

        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name))
                return name;

            var builder = new StringBuilder(name.Length + 1);
            if (!char.IsLetter(name[0]) && name[0] != '_')
                builder.Append('_');

            foreach (char character in name)
                builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');

            string identifier = builder.ToString();
            return CSharpKeywords.Contains(identifier) ? $"@{identifier}" : identifier;
        }

        private static string GetResourceRelativePath(string fullPath)
        {
            int resourcesIndex = fullPath.IndexOf("Resources", StringComparison.Ordinal);
            if (resourcesIndex < 0)
                return null;

            string relativePath = fullPath
                .Substring(resourcesIndex + "Resources".Length + 1)
                .Replace('\\', '/');
            return Path.ChangeExtension(relativePath, null);
        }
    }
}
